package bacmman.ui.gui.configurationIO;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import static bacmman.utils.Utils.SPECIAL_CHAR;

public class SaveDLModelGist {
    private JPanel namePanel;
    private JTextField name;
    private JPanel folderPanel;
    private JTextField folder;
    private JPanel urlPanel;
    private JTextField url;
    private JPanel descPanel;
    private JTextArea description;
    private JCheckBox publicJCB;
    private JButton cancel;
    private JButton OK;
    private JPanel panelMain;
    boolean canceled = false;

    public SaveDLModelGist() {
        KeyAdapter ke = new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (SPECIAL_CHAR.matcher(String.valueOf(c)).find()) {
                    e.consume();  // ignore event
                }
            }
        };
        name.addKeyListener(ke);
        folder.addKeyListener(ke);
    }

    public void display(JFrame parent, String title) {
        JDialog dia = new Dial(parent, title);
        dia.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        namePanel = new JPanel();
        namePanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(namePanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        namePanel.setBorder(BorderFactory.createTitledBorder("Name"));
        name = new JTextField();
        namePanel.add(name, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        folderPanel = new JPanel();
        folderPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(folderPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        folderPanel.setBorder(BorderFactory.createTitledBorder("Folder"));
        folder = new JTextField();
        folderPanel.add(folder, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        urlPanel = new JPanel();
        urlPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(urlPanel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        urlPanel.setBorder(BorderFactory.createTitledBorder("URL"));
        url = new JTextField();
        urlPanel.add(url, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        descPanel = new JPanel();
        descPanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        panelMain.add(descPanel, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        descPanel.setBorder(BorderFactory.createTitledBorder("Description"));
        description = new JTextArea();
        descPanel.add(description, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        publicJCB = new JCheckBox();
        publicJCB.setText("public");
        descPanel.add(publicJCB, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancel = new JButton();
        cancel.setText("Cancel");
        descPanel.add(cancel, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        OK = new JButton();
        OK.setText("OK");
        descPanel.add(OK, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

    private class Dial extends JDialog {
        Dial(JFrame parent, String title) {
            super(parent, title, true);
            getContentPane().add(panelMain);
            setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            pack();
            cancel.addActionListener(e -> {
                canceled = true;
                setVisible(false);
                dispose();
            });
            OK.addActionListener(e -> {
                canceled = false;
                setVisible(false);
                dispose();
            });
        }
    }

    public SaveDLModelGist setFolder(String folderName) {
        folder.setText(folderName);
        return this;
    }

    public SaveDLModelGist setName(String name) {
        this.name.setText(name);
        return this;
    }

    public SaveDLModelGist disableNameField() {
        this.name.setEnabled(false);
        return this;
    }

    public SaveDLModelGist disableFolderField() {
        this.folder.setEnabled(false);
        return this;
    }

    public SaveDLModelGist disableVisibleField() {
        this.publicJCB.setEnabled(false);
        return this;
    }

    public SaveDLModelGist setDescription(String description) {
        this.description.setText(description);
        return this;
    }

    public SaveDLModelGist setVisible(boolean visible) {
        this.publicJCB.setSelected(visible);
        return this;
    }

    public SaveDLModelGist setURL(String url) {
        this.url.setText(url);
        return this;
    }

    public boolean visible() {
        return publicJCB.isSelected();
    }

    public String name() {
        return name.getText();
    }

    public String folder() {
        return folder.getText();
    }

    public String description() {
        return description.getText();
    }

    public String url() {
        return url.getText();
    }
}
