/* 
 * Copyright (C) 2018 Jean Ollion
 *
 * This File is part of BACMMAN
 *
 * BACMMAN is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * BACMMAN is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with BACMMAN.  If not, see <http://www.gnu.org/licenses/>.
 */
package bacmman.plugins.plugins.measurements;

import bacmman.configuration.parameters.ObjectClassParameter;
import bacmman.configuration.parameters.Parameter;
import bacmman.data_structure.Measurements;
import bacmman.data_structure.SegmentedObject;
import bacmman.measurement.MeasurementKey;
import bacmman.measurement.MeasurementKeyObject;
import bacmman.plugins.Measurement;
import bacmman.plugins.Hint;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Jean Ollion
 */
public class BacteriaTrackingAttributes implements Measurement, Hint {
    protected ObjectClassParameter bacteria = new ObjectClassParameter("Object Class", -1, false, false).setHint("Select object class corresponding to bacteria");;
    protected Parameter[] parameters = new Parameter[]{bacteria};
    
    public BacteriaTrackingAttributes(){}
    
    public BacteriaTrackingAttributes(int bacteriaStructureIdx){
        this.bacteria.setSelectedIndex(bacteriaStructureIdx);
    }
    
    @Override
    public String getHintText() {
        return "Extract track attributes generated by the bacteria tracker";
    }
    
    @Override
    public int getCallObjectClassIdx() {
        return bacteria.getSelectedClassIdx();
    }
    @Override
    public boolean callOnlyOnTrackHeads() {
        return false;
    }
    @Override
    public List<MeasurementKey> getMeasurementKeys() {
        int structureIdx = bacteria.getSelectedClassIdx();
        ArrayList<MeasurementKey> res = new ArrayList<>();
        res.add(new MeasurementKeyObject("SizeRatio", structureIdx));
        res.add(new MeasurementKeyObject("TrackErrorSizeRatio", structureIdx));
        res.add(new MeasurementKeyObject("EndOfChannelContact", structureIdx));
        res.add(new MeasurementKeyObject("TruncatedDivision", structureIdx));
        return res;
    }

    @Override public void performMeasurement(SegmentedObject object) {
        Measurements m = object.getMeasurements();
        if (object.getAttribute("EndOfChannelContact")!=null) m.setValue("EndOfChannelContact", object.getAttribute("EndOfChannelContact", Double.NaN));
        else m.setValue("EndOfChannelContact", null); // remove
        if (object.getAttribute("TruncatedDivision")!=null) m.setValue("TruncatedDivision", object.getAttribute("TruncatedDivision", false));
        else m.setValue("TruncatedDivision", null); // remove
        if (object.getAttribute("SizeRatio")!=null)  m.setValue("SizeRatio", object.getAttribute("SizeRatio", Double.NaN));
        else m.setValue("SizeRatio", null); // remove
        if (Boolean.TRUE.equals(object.getAttribute("TrackErrorSizeRatio"))) m.setValue("TrackErrorSizeRatio", true);
        else m.setValue("TrackErrorSizeRatio", null); // remove
    }
    
    @Override
    public Parameter[] getParameters() {
        return parameters;
    }

    
    
}
